config/routes.rb
FirehoseApp::Application.routes.draw do

  root 'static_pages#index'
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, PicUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		# Pic.all -- Pic is the name of the database
		@pics = Pic.all;
	end

		# to make one new pic
	def new
		@pic = Pic.new
	end

	def create
		Pic.create(pics_params)
		redirect_to pics_path
	end

	# this is how to suck the params out when someone presses the submit button
	private

	def pics_params
		params.require(:pic).permit(:hour,:emotion,:learned,:image)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

# this is the page that is the index because I set it to
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextRI</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<!-- this is the navbar inverse -->
<div class="navbar navbar-inverse">

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <!-- <a class="brand" href="#">TextRI</a> -->
      <%= link_to 'TextRI', root_path, :class => 'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
		<ul class = "nav"> 
			<li><%= link_to 'My App', pics_path %></li>
			<li><%= link_to 'New Image', new_pic_path %></li>
		</ul>

      </div>
 
    </div>
  </div>
</div>




<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<h2>
	<!-- this is like var dump -->
	<% @pics.each do |pic|%>
	<div class="span4 text-centre helloBox">

		<h1 class="custom-font">
			Hour: <%= pic.hour %>
		</h1>
		<div class="text-center"><%= image_tag(pic.image) %></div>
		<h2>
			<br/>
			Emotion: <%= pic.emotion %>
			<br/><br/>
			Learned: <%= pic.learned %>

		</h2>

	</div>
	<% end %>
</h2>

app/views/pics/new.html.erb
<div class="span6 offset3 text-center helloBox">
	
	<h1 class="custom-font">
	Type a new post </h1>
	<br/>

	<%= simple_form_for @pic do |f|%>
		<%= f.input :hour, label: 'What time?', placeholder: '1, 2, 3 etc' %>
		
		<div class="label">Selfie</div>
		<div class="move-button" >
		<%= f.input :image, :label => false %>
		</div>
		
		<%= f.input :emotion, label: 'How did you feel?', placeholder: 'Stoked, Confused, Excited, Hungry, Sleepy, Happy', :as => :text %> 
		<!-- this is how you override it to make more texts :as => :text -->
		<!-- this is how you make placeholder -> placeholder: 'Stoked, Confused, Excited, Hungry, Sleepy, Happy'-->
		<%= f.input :learned, label: 'What did you learn?', placeholder: 'HTML, CSS, Rails, Ruby, Github' %>
		<br/>
		<%= f.submit 'Save', :class => 'btn btn-warning btn-large' %>
	<% end %>


</div>

app/views/static_pages/index.html.erb
<!-- this is a box that i can apply css styling to -->
<div class="span6 offset3 text-center helloBox">

	<h1 class="custom-font">Hi I'm Amanda</h1>

	<h2>Let us talk about emotions ... </h2>
	<%= link_to 'Launch rocket', pics_path, :class => 'btn btn-success btn-large' %>

</div>